### PR TITLE
Add support for creating a NimBLEClient from a NimBLEServer peer.

### PR DESCRIPTION
**Pull request by h2zero**
This allows the NimBLEServer instance to create a NimBLEClient instance to read/write form/to a connected peer. Only one instance is supported subsequent calls will overwrite the previous client connection information and data.

### CODE REVIEW

**Comment by h2zero** [comment]
@finger563 You may be interested in reviewing this, your feedback would be greatly appreciated.

**Comment by h2zero** [comment]
That shouldn't be necessary now because the client is created and managed by the server and `NimBLEDevice::deint(true)` will only manage the clients created through that interface. The server will delete the client instance when it is deleted so there should be no issues.

**Comment by h2zero** [comment]
@finger563 Did you perhaps test this at all?

**Comment by finger563** [comment]
@h2zero Unfortunately, I've not had time to yet. If you need, I'll be able to test late today or tomorrow.

**Comment by finger563** [comment]
@h2zero one change in behavior I'm seeing when using the new client instead of the one I was using before is that the initial connection (before auth is complete) now returns failure to get generic access service from the client:

Disconnect and reconnect and it works fine.

CleanShot 2024-12-05 at 08 07 37

So that's something that ideally could be fixed?

**Comment by h2zero** [comment]
Thanks, not sure why that errored, would need to see logging with info messages on.

**Comment by finger563** [comment]
@h2zero 

Here are some additional logs turned on esp-nimble-cpp:
CleanShot 2024-12-05 at 10 13 59

**Comment by h2zero** [comment]
Thanks, found the issue.

**Comment by finger563** [comment]
@h2zero Thanks, confirmed it's fixed :)
CleanShot 2024-12-05 at 13 19 01

**Review by finger563 — APPROVED** [review]
Works well in my testing :)

**Comment by h2zero** [comment]
Great, thanks!  I'm considering removing the server name read to go along with this as it seems redundant and bloats the code.

**Pull request merged**
