### PR TITLE
Used more stable arduino detection methods

### PR DESCRIPTION
**Pull request by AronRubin**
I have a project that includes both Arduino as a component and esp-nimble-cpp in an ESP-IDF v4.4 environment. There were two issues preventing that from working. First the ARDUINO_ARCH_ESP32 macro is defined on the arduino component compilation command line and seems not to carry over to other components reliably. The second is the conditional PRIV_REQUIRES of arduino in CMakeLists.txt failed to account for the IDF's dependency gathering phase of configuring. I have remedied both issues. Additionally, I made the CMakeLists.txt more current. Sorry about any style violations in that last step.

### CODE REVIEW

**Comment by h2zero** [comment]
Awesome, thanks for this! I've been meaning to cleanup that cmake file for a while.

**Comment by h2zero** [comment]
@AronRubin This looks and works fine I wonder if you could apply the same ardruino macro detection to the other checks in the files, i.e NimBLElog.h.

**Comment by AronRubin** [comment]
@h2zero I would absolutely recommend using macros from sdkconfig.h for conditional compile. The ARDUINO_ARCH_ESP32 is an artifact of target_compile_options within arduino-esp32/CMakeLists.txt. Something in the IDF CMake process would have to manually propagate those over or mark them as imported or interface libraries.

**Comment by h2zero** [comment]
Thanks, I will update the rest of the file that use that macro.

**Pull request merged**
