### PR TITLE
Support duplicate characteristics 

### PR DESCRIPTION
**Pull request by DavidJRobertson**
See #35

### CODE REVIEW

**Comment by h2zero** [comment]
Thanks for this! Saves me some time 😄 

Looks good to me.

**Review by h2zero — APPROVED** [review]
Looks great, exactly what I had in mind.

**Comment by h2zero** [comment]
Please let me know when you're ready for me to merge. I wouldn't want to merge before your done with changes.

**Comment by DavidJRobertson** [comment]
Thanks - I'm done with it.

**Comment by h2zero** [comment]
Merged, thanks again!

**Pull request merged**
